// <auto-generated />
using System;
using GuatexWoocommerce;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuatexWoocommerce.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230929045256_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GuatexWoocommerce.Database.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PuntoCobertura")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("GuatexWoocommerce.Database.GuiasGeneradas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Anulada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CantidadPiezas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoCobro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDestino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoOrigen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescripcionEnvio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DireccionDestinatario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DireccionRemitente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GuiaActual")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("IdOrden")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("NumeroGuia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PesoTotal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remitente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoDestinatario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoRemitente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TotalGuias")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Guias");
                });
#pragma warning restore 612, 618
        }
    }
}
